[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
rke2_token=Rke2ClusterClusterToken2026!
rke2_version=v1.30.2+rke2r1

[haproxy]
haproxy-01 ansible_host=192.168.1.11 keepalived_role=MASTER keepalived_priority=101
haproxy-02 ansible_host=192.168.1.12 keepalived_role=BACKUP keepalived_priority=100

[k8s_primary_master]
k8s-master-01 ansible_host=192.168.1.21

[k8s_secondary_masters]
k8s-master-02 ansible_host=192.168.1.22
k8s-master-03 ansible_host=192.168.1.23

[k8s_masters:children]
k8s_primary_master
k8s_secondary_masters

[k8s_workers]
k8s-worker-01 ansible_host=192.168.1.31
k8s-worker-02 ansible_host=192.168.1.32
k8s-worker-03 ansible_host=192.168.1.33

[k8s_cluster:children]
k8s_masters
k8s_workers

[postgres_nodes]
postgres-01 ansible_host=192.168.1.41
postgres-02 ansible_host=192.168.1.42

[minio_nodes]
minio ansible_host=192.168.1.51

[redis_nodes]
redis ansible_host=192.168.1.61

[elk_nodes]
elk ansible_host=192.168.1.71