---
- name: Update APT Package Cache & Upgrade System
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Fundamental Packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - ufw
      - sysstat
      - net-tools
      - software-properties-common
    state: present

- name: Disable Swap Space
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove Swap Entry from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#\\s]+\\s+[^#\\s]+\\s+swap\\s+.*)$'
    replace: '# \\1'

- name: Tune Linux Kernel System Controls
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.ipv4.ip_nonlocal_bind', value: '1' }
    - { key: 'fs.file-max', value: '2097152' }
    - { key: 'net.core.somaxconn', value: '65535' }